### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by JJGNB** [BOYang-pro/LFDT-Fusion#2]
感谢作者的工作！我对于代码有一些疑问，模型训练不应该是约束噪声吗，为什么代码中模型返回的是noise_image而不是noise？

**Comment by BOYang-pro** [comment]
确实，这里应该返回的是 noise，而不是 noise_image。这是我们在整理代码阶段的一个笔误，我们已经重新更新了代码，十分感谢您能及时反馈这个问题。
